[default]
address = "0.0.0.0"
port = 8080
temp_dir = "./tmp"
cli_colors = true
log_level = "normal"
template_dir = "templates"

# Picture upload limits - we can specify extensions
limits.file = "16MiB"

[debug]
address = "127.0.0.1"
