[default]
address = "0.0.0.0"
port = 8080
temp_dir = "./tmp"
cli_colors = true
log_level = "normal"

[limits]
# Picture upload limits - we can specify extensions
file = "16MiB"

[debug]
address = "127.0.0.1"