[default]
address = "0.0.0.0"
port = 8080
temp_dir = "/tmp"
cli_colors = true
log_level = "normal"
template_dir = "templates"

# Picture upload limits - we can specify extensions
limits.file = "16MiB"
# We also need to make data forms larger so that the picture can be sent
limits.data-form = "16MiB"

[debug]
address = "127.0.0.1"
temp_dir = "./tmp"
